server:
  port: 8888

spring:
  application:
    name: CLOUD-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pradeepnayak1988/pixogram-repo
          clone-on-start: true
          
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka